// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dR4nRMhgDzMjZ_XGMgpBNUtRGeqvXKA',
    appId: '1:190605335530:web:0af1be8348fe58f4f37093',
    messagingSenderId: '190605335530',
    projectId: 'grandmaproject-bdb29',
    authDomain: 'grandmaproject-bdb29.firebaseapp.com',
    storageBucket: 'grandmaproject-bdb29.appspot.com',
    measurementId: 'G-SCHZSB66DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuVLIvNWOioufc5gJXkN1-qTJdSXGsSSs',
    appId: '1:190605335530:android:7a4cee5cd5f056b0f37093',
    messagingSenderId: '190605335530',
    projectId: 'grandmaproject-bdb29',
    storageBucket: 'grandmaproject-bdb29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6gYSnEr-y79nzbILbQSR24_B-G71mgfo',
    appId: '1:190605335530:ios:d9bb259abf293f36f37093',
    messagingSenderId: '190605335530',
    projectId: 'grandmaproject-bdb29',
    storageBucket: 'grandmaproject-bdb29.appspot.com',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6gYSnEr-y79nzbILbQSR24_B-G71mgfo',
    appId: '1:190605335530:ios:bb02787041ee1fd7f37093',
    messagingSenderId: '190605335530',
    projectId: 'grandmaproject-bdb29',
    storageBucket: 'grandmaproject-bdb29.appspot.com',
    iosBundleId: 'com.example.projectapp.RunnerTests',
  );
}
